contentColumnType: string
fieldGroup: 21403b57-0519-407e-97a2-58440ba2b647 # Über mich
handle: aboutPortrait
instructions: ''
name: Portrait
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Bild auswählen'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1441d23a-77fd-4cb1-9e07-7deda2c44aca' # Bilder
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
